//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DernekKayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aidat
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Yil { get; set; }
        public Nullable<int> Tutar { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual User User { get; set; }
    }
}
