//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DernekKayit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DernekKayitEntities : DbContext
    {
        public DernekKayitEntities()
            : base("name=DernekKayitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aidat> Aidat { get; set; }
        public DbSet<Cocuk> Cocuk { get; set; }
        public DbSet<EgitimDurum> EgitimDurum { get; set; }
        public DbSet<Es> Es { get; set; }
        public DbSet<Kasa> Kasa { get; set; }
        public DbSet<KasaIslemTip> KasaIslemTip { get; set; }
        public DbSet<KasaIslemTur> KasaIslemTur { get; set; }
        public DbSet<Meslek> Meslek { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UyeDurum> UyeDurum { get; set; }
    }
}
