//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DernekKayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Aidat = new HashSet<Aidat>();
            this.Cocuk = new HashSet<Cocuk>();
            this.Es = new HashSet<Es>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> MeslekId { get; set; }
        public byte EgitimDurumId { get; set; }
        public byte DurumId { get; set; }
        public string AdSoyad { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string EvAdresi { get; set; }
        public string CepTel { get; set; }
        public string EvTel { get; set; }
        public string EPosta { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public bool MedeniHal { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Aidat> Aidat { get; set; }
        public virtual ICollection<Cocuk> Cocuk { get; set; }
        public virtual EgitimDurum EgitimDurum { get; set; }
        public virtual ICollection<Es> Es { get; set; }
        public virtual Meslek Meslek { get; set; }
        public virtual UyeDurum UyeDurum { get; set; }
    }
}
