//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DernekKayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeDurum
    {
        public UyeDurum()
        {
            this.User = new HashSet<User>();
        }
    
        public byte Id { get; set; }
        public string UyeDurum1 { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
